Rails:
  Enabled: true
AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'spec/*'
    - 'spec/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - !ruby/regexp /old_and_unused\.rb$/
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/Documentation:
Enabled: false